# Generated by Django 6.0 on 2025-12-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_gateway_order_id_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('authorized', 'Authorized'), ('paid', 'Paid'), ('failed', 'Failed')], default='initiated', max_length=20),
        ),
    ]
