# Generated by Django 6.0 on 2025-12-27 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0002_alter_category_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='productqa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='crystal_cat_slug_535f71_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='crystal_pro_slug_5c562b_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='crystal_pro_is_acti_b329c3_idx',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crystal.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productqa',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crystal_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
