# Generated by Django 6.0 on 2025-12-27 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0007_alter_productqa_options_alter_productreview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productqa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='crystal_pro_slug_5c562b_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='crystal_pro_is_acti_b329c3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_in_homepage',
            field=models.BooleanField(default=False, verbose_name='Show in Homepage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Length (cm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Width (cm)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
