# Generated by Django 6.0 on 2026-01-19 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='related_crystals',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='related_worships',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_crystal_icons',
            field=models.JSONField(default=list, help_text="Example: ['amethyst.png','rudraksha.png']"),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.blogcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='short_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
