# Generated by Django 6.0 on 2026-01-19 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogcategory_options_alter_blogpost_options_and_more'),
        ('crystal', '0008_alter_productqa_options_alter_productreview_options_and_more'),
        ('worship', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['name'], 'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='related_crystal_icons',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='short_description',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='show_in_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_crystals',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='crystal.category'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_worship',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='worship.category'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
