# Generated by Django 6.0 on 2025-12-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_generated',
            field=models.BooleanField(default=False),
        ),
    ]
