# Generated by Django 6.0 on 2025-12-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_stock_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_initiated',
            field=models.BooleanField(default=False),
        ),
    ]
