# Generated by Django 6.0 on 2026-01-13 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_refund_initiated_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image_url',
        ),
    ]
